require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe JamGroupMembersController, type: :controller do
  fixtures :all
  login_user

  # This should return the minimal set of attributes required to create a valid
  # JamGroupMember. As you add validations to JamGroupMember, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JamGroupMembersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all jam_group_members as @jam_group_members" do
      jam_group_member = FactoryGirl.create(:jam_group_member)
      get :index, params: {}, session: valid_session
      expect(assigns(:jam_group_members)).to eq(JamGroupMember.all)
    end
  end

  describe "GET #show" do
    it "assigns the requested jam_group_member as @jam_group_member" do
      jam_group_member = FactoryGirl.create(:jam_group_member)
      get :show, params: {id: jam_group_member.to_param}, session: valid_session
      expect(assigns(:jam_group_member)).to eq(jam_group_member)
    end
  end

  describe "GET #new" do
    it "assigns a new jam_group_member as @jam_group_member" do
      get :new, params: {}, session: valid_session
      expect(assigns(:jam_group_member)).to be_a_new(JamGroupMember)
    end
  end

  describe "GET #edit" do
    it "assigns the requested jam_group_member as @jam_group_member" do
      jam_group_member = FactoryGirl.create(:jam_group_member)
      get :edit, params: {id: jam_group_member.to_param}, session: valid_session
      expect(assigns(:jam_group_member)).to eq(jam_group_member)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "redirects to the created jam_group_member" do
        jam_group = FactoryGirl.create(:jam_group)
        profile = FactoryGirl.create(:profile)
        post :create, params: {jam_group_member: {profile: profile.id, jam_group: jam_group.id, invited_by: profile.id}}, session: valid_session
        expect(response).to have_http_status(:ok)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved jam_group_member as @jam_group_member" do
        post :create, params: {jam_group_member: invalid_attributes}, session: valid_session
        expect(assigns(:jam_group_member)).to be_a_new(JamGroupMember)
      end

      it "re-renders the 'new' template" do
        post :create, params: {jam_group_member: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested jam_group_member" do
        jam_group_member = FactoryGirl.create(:jam_group_member)
        put :update, params: {id: jam_group_member.to_param, jam_group_member: new_attributes}, session: valid_session
        jam_group_member.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested jam_group_member as @jam_group_member" do
        jam_group_member = FactoryGirl.create(:jam_group_member)
        put :update, params: {id: jam_group_member.id, jam_group_member: new_attributes}, session: valid_session
        expect(assigns(:jam_group_member)).to eq(jam_group_member)
      end

      it "redirects to the jam_group_member" do
        jam_group_member = FactoryGirl.create(:jam_group_member)
        put :update, params: {id: jam_group_member.id, jam_group_member: new_attributes}, session: valid_session
        expect(response).to redirect_to(jam_group_member)
      end
    end

    context "with invalid params" do
      it "assigns the jam_group_member as @jam_group_member" do
        jam_group_member = FactoryGirl.create(:jam_group_member)
        put :update, params: {id: jam_group_member.to_param, jam_group_member: invalid_attributes}, session: valid_session
        expect(assigns(:jam_group_member)).to eq(jam_group_member)
      end

      it "re-renders the 'edit' template" do
        jam_group_member = FactoryGirl.create(:jam_group_member)
        put :update, params: {id: jam_group_member.to_param, jam_group_member: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested jam_group_member" do
      jam_group_member = FactoryGirl.create(:jam_group_member)
      expect {
        delete :destroy, params: {id: jam_group_member.to_param}, session: valid_session
      }.to change(JamGroupMember, :count).by(-1)
    end

    it "redirects to the jam_group_members list" do
      jam_group_member = FactoryGirl.create(:jam_group_member)
      delete :destroy, params: {id: jam_group_member.to_param}, session: valid_session
      expect(response).to redirect_to(jam_group_members_url)
    end
  end

end
